Prine-134 Add pi status to admin tool
bet-smart-parking/smart-parking-frontend pull request #133
Opened 2020-08-26 08:49 UTC by davidheimgartner

Run "yarn install" to install moment.js

2020-08-28 13:48 UTC, hirsch88 requested changes

2020-08-28 13:48 UTC, hirsch88 commented on package.json
> +    "moment": "^2.27.0",
moment is a huge lib and most of the time we only need like 1 - 5 % of it. there is smaller and faster brother of moment called luxon
https://moment.github.io/luxon/

2020-08-28 13:48 UTC, hirsch88 commented on src/app/pages/admin/AdminDashboard.vue
> +.gateControlDeviceContainer {
Looks like duplicated code :-)
try to create a component for that

2020-08-28 15:31 UTC, prine commented on src/app/pages/admin/AdminDashboard.vue
> +.gateControlDeviceContainer {
Oops, I just forgot to delete the css. It is already an external component-

2020-09-01 09:17 UTC, prine commented on package.json
> +    "moment": "^2.27.0",
We have exchanged moment with luxon

2020-09-01 11:32 UTC, merged

2020-09-04 07:47 UTC, bets-bal commented
:tada: This PR is included in version 1.35.0 :tada:

The release is available on [GitHub release](https://github.com/bet-smart-parking/smart-parking-frontend/releases/tag/v1.35.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: